unpackaged/main/default/objects/Gearset_Deployment__c/Gearset_Deployment__c.object-meta.xml
<CustomObject>
    <label>Gearset Deployment</label>
    <nameField>
        <label>Gearset Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gearset Deployments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Gearset_Deployment__c/fields/Deployment_Id__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Id__c</fullName>
    <externalId>true</externalId>
    <label>Deployment Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Gearset_Deployment__c/fields/Friendly_Name__c.field-meta.xml
<CustomField>
    <fullName>Friendly_Name__c</fullName>
    <label>Friendly Name</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Gearset_Deployment__c/fields/Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>Owner_Name__c</fullName>
    <label>Owner Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Gearset_Deployment__c/fields/Salesforce_Final_Deployment_Id__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Final_Deployment_Id__c</fullName>
    <externalId>true</externalId>
    <label>Salesforce Final Deployment Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Gearset_Deployment__c/fields/Source_Metadata_Location__c.field-meta.xml
<CustomField>
    <fullName>Source_Metadata_Location__c</fullName>
    <label>Source Metadata Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Gearset_Deployment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Gearset_Deployment__c/fields/Target_Metadata_Location__c.field-meta.xml
<CustomField>
    <fullName>Target_Metadata_Location__c</fullName>
    <label>Target Metadata Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Gearset_Deployment__c/fields/Target_Username__c.field-meta.xml
<CustomField>
    <fullName>Target_Username__c</fullName>
    <label>Target Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Gearset_Deployment__c/fields/Time_of_Deployment__c.field-meta.xml
<CustomField>
    <fullName>Time_of_Deployment__c</fullName>
    <label>Time of Deployment</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Gearset_Deployment__c/fields/Triggered_By__c.field-meta.xml
<CustomField>
    <fullName>Triggered_By__c</fullName>
    <label>Triggered By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Gearset_Deployment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>AutomaticallyPromotedCiValidation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/GearsetReportingDataImporter.cls
public with sharing class GearsetReportingDataImporter {
    public void executeImport() {
        DateTime lastDateTime = getNewStartTime();
        List<Gearset_Deployment__c> latestDetails = getLatestDetails(lastDateTime);
        saveData(latestDetails);
    }

    public DateTime getNewStartTime() {
        DateTime response = null;

        List<Gearset_Deployment__c> deployments = [SELECT Time_of_Deployment__c FROM Gearset_Deployment__c ORDER BY Time_of_Deployment__c DESC LIMIT 1];

        if (deployments.size() == 1) {
            response = deployments[0].Time_of_Deployment__c;
        }

        return response;
    }

    public List<Gearset_Deployment__c> getLatestDetails(Datetime lastDateTime) {
        List<Gearset_Deployment__c> results = new List<Gearset_Deployment__c>();
        Deployment data;

        if (lastDateTime == null) {
            lastDateTime = Datetime.now().addMonths(-6);
        }

        HttpRequest request = createReportingRequest(lastDateTime);
        Http http = new Http();
        HttpResponse response = http.send(request);

        data = (Deployment)JSON.deserialize(response.getBody().replace('"Date"', '"DeploymentDate"'), Deployment.class);

        if (data != null && data.Deployments != null) {
            System.debug('Found ' + data.Deployments.size() + ' records');
            for (DeploymentDetails thisDeployment : data.Deployments) {
                results.add(thisDeployment.convertToSObject());
            }
        }

        return results;
    }

    public void saveData(List<Gearset_Deployment__c> data) {
        insert data;
    }

    private HttpRequest createReportingRequest(DateTime lastDateTime) {
        HttpRequest req = new HttpRequest();
        String encodedStartDate = EncodingUtil.urlEncode(String.valueOf(lastDateTime).replace(' ', 'T'), 'UTF-8');
        String encodedEndDate = EncodingUtil.urlEncode(String.valueOf(Datetime.now()).replace(' ', 'T'), 'UTF-8');
        String url = 'deployment-frequency?StartDate=' + encodedStartDate + 'Z&EndDate=' + encodedEndDate + 'Z';
        req.setEndpoint('callout:Gearset_Reporting_API/' + url);
        req.setMethod('GET');
        req.setTimeout(120000);

        return req;
    }

    public class Deployment {
        List<DeploymentDetails> Deployments { get; set; }

        public Deployment() {
            Deployments = new List<DeploymentDetails>();
        }
    }

    public class DeploymentDetails {
        public String DeploymentId { get; set; }
        public String Status { get; set; }
        public String Name { get; set; }
        public String Owner { get; set; }
        public String TriggeredBy { get; set; }
        public DateTime DeploymentDate { get; set; }
        public String FriendlyName { get; set; }
        public String SourceUsername { get; set; }
        public String SourceMetadataLocationType { get; set; }
        public String TargetUsername { get; set; }
        public String TargetMetadataLocationType { get; set; }
        public String DeploymentType { get; set; }
        public Id SalesforceFinalDeploymentId { get; set; }

        public Gearset_Deployment__c convertToSObject() {
            Gearset_Deployment__c dbRecord = new Gearset_Deployment__c();            
            dbRecord.Name = this.Name.length() <= 80 ? this.Name : this.Name.substring(0, 80);
            dbRecord.Deployment_Id__c = this.DeploymentId;
            dbRecord.Friendly_Name__c = this.FriendlyName;
            dbRecord.Owner_Name__c = this.Owner;
            dbRecord.Salesforce_Final_Deployment_Id__c = this.SalesforceFinalDeploymentId;
            dbRecord.Source_Metadata_Location__c = this.SourceMetadataLocationType;
            dbRecord.Status__c = this.Status;
            dbRecord.Target_Metadata_Location__c = this.TargetMetadataLocationType;
            dbRecord.Target_Username__c = this.TargetUsername;
            dbRecord.Time_of_Deployment__c = this.DeploymentDate;
            dbRecord.Triggered_By__c = this.TriggeredBy;
            dbRecord.Type__c = this.DeploymentType;

            return dbRecord;
        }
    }
}