unpackaged/main/default/objects/Gearset_Deployment__c/Gearset_Deployment__c.object-meta.xml
<CustomObject>
    <label>Gearset Deployment</label>
    <nameField>
        <label>Gearset Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gearset Deployments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Gearset_Deployment_Summary__c/Gearset_Deployment_Summary__c.object-meta.xml
<CustomObject>
    <label>Gearset Deployment Summary</label>
    <nameField>
        <label>Gearset Deployment Stats Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gearset Deployment Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Gearset_Environment__mdt/Gearset_Environment__mdt.object-meta.xml
<CustomObject>
    <label>Gearset Environment</label>
    <pluralLabel>Gearset Environments</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Gearset_Environment__mdt/fields/Environment_Id__c.field-meta.xml
<CustomField>
    <fullName>Environment_Id__c</fullName>
    <label>Environment Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Gearset_Pipeline__mdt/Gearset_Pipeline__mdt.object-meta.xml
<CustomObject>
    <label>Gearset Pipeline</label>
    <pluralLabel>Gearset Pipelines</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Gearset_Pipeline__mdt/fields/Pipeline_ID__c.field-meta.xml
<CustomField>
    <fullName>Pipeline_ID__c</fullName>
    <label>Pipeline ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Gearset_Reporting_Options__mdt/Gearset_Reporting_Options__mdt.object-meta.xml
<CustomObject>
    <label>Gearset Reporting Options</label>
    <pluralLabel>Gearset Reporting Options</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Gearset_Reporting_Options__mdt/fields/Months_To_Retrieve__c.field-meta.xml
<CustomField>
    <fullName>Months_To_Retrieve__c</fullName>
    <description>The previous time period for which data should be retrieved.</description>
    <inlineHelpText>Some heuristics apply to a previous date in time. For example, a deployment becomes a failed deployment when it is reverted or fixed. The date of the failed deployment is the original deployment time, not the date of the correction. This value controls how many previous months to query when retrieving data.</inlineHelpText>
    <label>Months To Retrieve</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GSR_Change_Failed_PR__c/GSR_Change_Failed_PR__c.object-meta.xml
<CustomObject>
    <label>Change Failed Pull Request</label>
    <nameField>
        <displayFormat>GSCFPR-{0000000}</displayFormat>
        <label>Change Failed PR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Failed Pull Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GSR_Change_Failed_PR__c/fields/Gearset_Deployment__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Deployment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gearset Deployment</label>
    <referenceTo>Gearset_Deployment__c</referenceTo>
    <relationshipName>Pull_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/GSR_Change_Failure_Summary__c/GSR_Change_Failure_Summary__c.object-meta.xml
<CustomObject>
    <label>Change Failure Summary</label>
    <nameField>
        <displayFormat>GSRCFS-{00000000}</displayFormat>
        <label>Change Failure Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Failure Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GSR_Lead_Time_PR__c/GSR_Lead_Time_PR__c.object-meta.xml
<CustomObject>
    <label>Lead Time Pull Request</label>
    <nameField>
        <displayFormat>GSLTPR-{000000}</displayFormat>
        <label>Lead Time Pull Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Time Pull Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GSR_Lead_Time_PR__c/fields/Pipeline_Id__c.field-meta.xml
<CustomField>
    <fullName>Pipeline_Id__c</fullName>
    <label>Pipeline Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GSR_Lead_Time_Summary__c/GSR_Lead_Time_Summary__c.object-meta.xml
<CustomObject>
    <label>Lead Time Summary</label>
    <nameField>
        <displayFormat>GRLTS-{0000000}</displayFormat>
        <label>Lead Time Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Time Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GSR_Time_To_Restore_PR__c/GSR_Time_To_Restore_PR__c.object-meta.xml
<CustomObject>
    <label>Time To Restore Pull Request</label>
    <nameField>
        <displayFormat>GSTRPR-{0000000}</displayFormat>
        <label>Time To Restore Pull Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time To Restore Pull Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GSR_Time_To_Restore_Summary__c/GSR_Time_To_Restore_Summary__c.object-meta.xml
<CustomObject>
    <label>Time To Restore Summary</label>
    <nameField>
        <displayFormat>GSRTTR-{00000000}</displayFormat>
        <label>Time To Restore Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time To Restore Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/GearsetImporterOrchestrator.cls
public with sharing class GearsetImporterOrchestrator implements Schedulable {
    public void execute(SchedulableContext context) {
        // get all pipelines and environments
        List<Gearset_Pipeline__mdt> pipelines = [SELECT Pipeline_ID__c FROM Gearset_Pipeline__mdt];
        List<Gearset_Environment__mdt> environments = [SELECT Environment_Id__c FROM Gearset_Environment__mdt];
        List<Gearset_Reporting_Options__mdt> options = [SELECT Months_To_Retrieve__c FROM Gearset_Reporting_Options__mdt WHERE DeveloperName = 'Standard_Options'];
        List<String> pipelineIds = new List<String>(), environmentIds = new List<String>();
        Integer pastMonths = 1;
        for (Gearset_Pipeline__mdt pipeline : pipelines) {
            pipelineIds.add(pipeline.Pipeline_ID__c);
        }
        for (Gearset_Environment__mdt environment : environments) {
            environmentIds.add(environment.Environment_Id__c);
        }
        if (options != null && options.size() == 1) {
            pastMonths = Integer.valueOf(options[0].Months_To_Retrieve__c);
        }
        pastMonths = pastMonths * -1;

        // others refer to this data, so do this one synchronously
        GearsetReportingDataImporter grImporter = new GearsetReportingDataImporter();
        grImporter.executeImport();
        GearsetDeploymentStatsImporter deploymentSummaryImporter = new GearsetDeploymentStatsImporter();
        System.enqueueJob(deploymentSummaryImporter);
        GearsetChangeFailureDataImporter cfrImporter = new GearsetChangeFailureDataImporter(environmentIds, 0, pastMonths);
        System.enqueueJob(cfrImporter);
        GearsetChangeFailureStatsImporter cfrSummaryImporter = new GearsetChangeFailureStatsImporter(environmentIds, 0, pastMonths);
        System.enqueueJob(cfrSummaryImporter);
        GearsetLeadTimeDataImporter ltImporter = new GearsetLeadTimeDataImporter(pipelineIds, 0, pastMonths);
        System.enqueueJob(ltImporter);
        GearsetLeadTimeStatsImporter ltsImporter = new GearsetLeadTimeStatsImporter(pipelineIds, 0, pastMonths);
        System.enqueueJob(ltsImporter);
        GearsetRestoreTimeDataImporter rtImporter = new GearsetRestoreTimeDataImporter(environmentIds, 0, pastMonths);
        System.enqueueJob(rtImporter);
        GearsetRestoreTimeStatsImporter rtsImporter = new GearsetRestoreTimeStatsImporter(environmentIds, 0, pastMonths);
        System.enqueueJob(rtsImporter);

        /*List<Gearset_Deployment__c> gd = [SELECT Id FROM Gearset_Deployment__c];
        delete gd;
        List<Gearset_Deployment_Summary__c> gds = [SELECT Id FROM Gearset_Deployment_Summary__c];
        delete gds;
        List<GSR_Change_Failed_PR__c> cfp = [SELECT Id FROM GSR_Change_Failed_PR__c];
        delete cfp;
        List<GSR_Change_Failure_Summary__c> cfs = [SELECT Id FROM GSR_Change_Failure_Summary__c];
        delete cfs;
        List<GSR_Lead_Time_PR__c> ltp = [SELECT Id FROM GSR_Lead_Time_PR__c];
        delete ltp;
        List<GSR_Lead_Time_Summary__c> lts = [SELECT Id FROM GSR_Lead_Time_Summary__c];
        delete lts;
        List<GSR_Time_To_Restore_PR__c> ttrp = [SELECT Id FROM GSR_Time_To_Restore_PR__c];
        delete ttrp;
        List<GSR_Time_To_Restore_Summary__c> ttrs = [SELECT Id FROM GSR_Time_To_Restore_Summary__c];
        delete ttrs;*/
    }
}