unpackaged/main/default/objects/Gearset_Deployment_Summary__c/Gearset_Deployment_Summary__c.object-meta.xml
<CustomObject>
    <label>Gearset Deployment Summary</label>
    <nameField>
        <label>Gearset Deployment Stats Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gearset Deployment Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Gearset_Deployment_Summary__c/fields/Cumulative_Failed_Deployments__c.field-meta.xml
<CustomField>
    <fullName>Cumulative_Failed_Deployments__c</fullName>
    <label>Cumulative Failed Deployments</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Gearset_Deployment_Summary__c/fields/Cumulative_Successful_Deployments__c.field-meta.xml
<CustomField>
    <fullName>Cumulative_Successful_Deployments__c</fullName>
    <label>Cumulative Successful Deployments</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/GearsetDeploymentSummaryTrigger_Test.cls
@isTest
public class GearsetDeploymentSummaryTrigger_Test {
    @isTest
    private static void before_insert_triggered_correctly() {
        Gearset_Deployment_Summary__c record = new Gearset_Deployment_Summary__c();
        record.Date__c = Date.newInstance(2021, 7, 2);
        record.Cumulative_Successful_Deployments__c = 3;
        record.Cumulative_Failed_Deployments__c = 1;
        
        Test.startTest();
        insert record;
        Test.stopTest();

        System.assertEquals(3, record.Cumulative_Successful_Deployments__c, 'successful value incorrect');
        System.assertEquals(1, record.Cumulative_Failed_Deployments__c, 'failed value incorrect');
    }
}