unpackaged/main/default/objects/Gearset_Deployment_Summary__c/Gearset_Deployment_Summary__c.object-meta.xml
<CustomObject>
    <label>Gearset Deployment Summary</label>
    <nameField>
        <label>Gearset Deployment Stats Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gearset Deployment Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Gearset_Deployment_Summary__c/fields/Cumulative_Failed_Deployments__c.field-meta.xml
<CustomField>
    <fullName>Cumulative_Failed_Deployments__c</fullName>
    <label>Cumulative Failed Deployments</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Gearset_Deployment_Summary__c/fields/Cumulative_Successful_Deployments__c.field-meta.xml
<CustomField>
    <fullName>Cumulative_Successful_Deployments__c</fullName>
    <label>Cumulative Successful Deployments</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/GearsetDeploymentSummaryTriggerHandler_T.cls
@isTest
public class GearsetDeploymentSummaryTriggerHandler_T {
    @isTest
    private static void test_before_insert() {
        List<Gearset_Deployment_Summary__c> records = new List<Gearset_Deployment_Summary__c>();
        Gearset_Deployment_Summary__c thisRecord = new Gearset_Deployment_Summary__c();
        thisRecord.Date__c = Date.newInstance(13, 7, 2022);
        thisRecord.Cumulative_Successful_Deployments__c = 3;
        thisRecord.Cumulative_Failed_Deployments__c = 2;
        records.add(thisRecord);

        Test.startTest();
        GearsetDeploymentSummaryTriggerHandler.beforeInsert(records);
        Test.stopTest();

        System.assertEquals(3, thisRecord.Cumulative_Successful_Deployments__c, 'successful total incorrect');
        System.assertEquals(2, thisRecord.Cumulative_Failed_Deployments__c, 'failed total incorrect');
    }
}