unpackaged/main/default/objects/Gearset_Deployment_Summary__c/Gearset_Deployment_Summary__c.object-meta.xml
<CustomObject>
    <label>Gearset Deployment Summary</label>
    <nameField>
        <label>Gearset Deployment Stats Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gearset Deployment Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Gearset_Deployment_Summary__c/fields/Cumulative_Failed_Deployments__c.field-meta.xml
<CustomField>
    <fullName>Cumulative_Failed_Deployments__c</fullName>
    <label>Cumulative Failed Deployments</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Gearset_Deployment_Summary__c/fields/Cumulative_Successful_Deployments__c.field-meta.xml
<CustomField>
    <fullName>Cumulative_Successful_Deployments__c</fullName>
    <label>Cumulative Successful Deployments</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/GearsetDeploymentSummaryTriggerHandler.cls
public with sharing class GearsetDeploymentSummaryTriggerHandler {
    public static void beforeInsert(List<Gearset_Deployment_Summary__c> newRecords) {
        Map<Date, Gearset_Deployment_Summary__c> recordMap = new Map<Date, Gearset_Deployment_Summary__c>();
        List<Date> sortedDateList = new List<Date>();

        for (Gearset_Deployment_Summary__c thisRecord : newRecords) {
            recordMap.put(thisRecord.Date__c, thisRecord);
            sortedDateList.add(thisRecord.Date__c);
        }

        sortedDateList.sort();
        Decimal currentSuccessTotal = 0, currentFailedTotal = 0;

        List<Gearset_Deployment_Summary__c> prevRecords = [SELECT Date__c, Cumulative_Successful_Deployments__c, Cumulative_Failed_Deployments__c FROM Gearset_Deployment_Summary__c ORDER BY Date__c DESC LIMIT 1];

        if (prevRecords.size() == 1) {
            currentSuccessTotal = prevRecords[0].Cumulative_Successful_Deployments__c;
            currentFailedTotal = prevRecords[0].Cumulative_Failed_Deployments__c;
        }

        for (Date thisDeploymentDate : sortedDateList) {
            Gearset_Deployment_Summary__c thisDeployment = recordMap.get(thisDeploymentDate);

            thisDeployment.Cumulative_Successful_Deployments__c += currentSuccessTotal;
            thisDeployment.Cumulative_Failed_Deployments__c += currentFailedTotal;

            currentSuccessTotal = thisDeployment.Cumulative_Successful_Deployments__c;
            currentFailedTotal = thisDeployment.Cumulative_Failed_Deployments__c;
        }
    }
}